name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - static-web-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_WAVE_0C9165E0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/code/serverless/static-web-app/web"
          api_location: "/code/serverless/static-web-app/api"
          output_location: "build"
